// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK2vXBpZCP_38uXyCXagW5epxbWTsWdQs',
    appId: '1:595087077020:web:e62e32b26d1b2a195c0759',
    messagingSenderId: '595087077020',
    projectId: 'causons-007',
    authDomain: 'causons-007.firebaseapp.com',
    storageBucket: 'causons-007.appspot.com',
    measurementId: 'G-ZCDGBB17S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmICybj9UDx_qZ8YWuOyq8D8qy96S5f_8',
    appId: '1:595087077020:android:7bd537cbba275cbb5c0759',
    messagingSenderId: '595087077020',
    projectId: 'causons-007',
    storageBucket: 'causons-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9WDUUIzzXEDRxgSe1t-TXBa10pRnwXyQ',
    appId: '1:595087077020:ios:10176f63cc8686335c0759',
    messagingSenderId: '595087077020',
    projectId: 'causons-007',
    storageBucket: 'causons-007.appspot.com',
    iosBundleId: 'com.example.causons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9WDUUIzzXEDRxgSe1t-TXBa10pRnwXyQ',
    appId: '1:595087077020:ios:10176f63cc8686335c0759',
    messagingSenderId: '595087077020',
    projectId: 'causons-007',
    storageBucket: 'causons-007.appspot.com',
    iosBundleId: 'com.example.causons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK2vXBpZCP_38uXyCXagW5epxbWTsWdQs',
    appId: '1:595087077020:web:9ee4c7293c9c355c5c0759',
    messagingSenderId: '595087077020',
    projectId: 'causons-007',
    authDomain: 'causons-007.firebaseapp.com',
    storageBucket: 'causons-007.appspot.com',
    measurementId: 'G-F1NTRT2KSY',
  );

}